//meta data
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//auth
import { SessionProvider } from 'next-auth/react'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/shared/auth'

//styling
import '../styles'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  return (
    <SessionProvider session={session}>
      <html lang='kr'>
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  )
}
